# Site settings
title: MyBetterWeb.site
slogan: "Website Design | eCommerce | SEO"
description: "We build seo-optimized and mobile-friendly websites designed to perform across all devices. Generate leads or sales from customers on desktop computers or their phones."
keywords: ""
author: Peranakan Francis
baseurl: "/"
url: "https://mybetterweb.site"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-import
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-menus
  - jekyll-archives
compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]
social:
  name: peranakafrancis
  links:
    - https://twitter.com/peranakafrancis
    - https://www.facebook.com/peranakafrancis
    - https://www.linkedin.com/in/peranakafrancis
    - https://plus.google.com/+peranakafrancis
    - https://github.com/peranakafrancis
    - https://keybase.io/peranakafrancis
    - https://wa.me/60142137507
    - https://m.me/peranakafrancis
twitter:
  username: peranakanfrancis
  card: summary
profile: true
incremental: true
livereload: true
time_zone: Asia/Katmandul
destination: public
source:
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
hightlighter: rouge
sass:
  sass_dir:
  style: compressed
excludes: [ README.md, node_modules, Gemfile* ]
