# Site settings
title: MyBetterWeb.site
slogan: "Web Development | eCommerce | Digital Marketing | Video Editing"
description: "We build seo-optimized and mobile-friendly websites designed to perform across all devices. Generate leads or sales from customers on desktop computers or their phones."
keywords: "digital marketing service in malaysia, website development in malaysia, web design in nepal, holiday video editing in malaysia, drone video editing in nepal, email marketing in malaysia, search engine optimization service in nepal, facebook ads service in nepal, google amp website in malaysia"
logo: img/logo-transparent.png
baseurl: ""
url: "https://mybetterweb.site"
permalink : pretty

# jekyll gems
plugins:
#  - jekyll-cloudinary
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-cloudinary
  
# cloudinary configuration  
cloudinary:
  cloud_name: "aboutmybetterweb"
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 640
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"

cloudinary:
  cloud_name: "aboutmybetterweb"
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"

# compress html
encoding: "utf-8"
compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]

# metadata
author: Peranakan Francis
social:
  name: MyBetterWeb
  links:
    - https://twitter.com/peranakafrancis
    - https://www.facebook.com/mybetterweb.site
    - https://www.linkedin.com/in/peranakafrancis
    - https://instagram.com/mybetterweb.site
    - https://github.com/peranakafrancis
    - https://keybase.io/peranakafrancis
    - https://wa.me/9779823034701
    - https://m.me/mybetterweb.site
twitter:
  username: peranakanfrancis
  card: summary
facebook:
  app_id: 150284722314875
  admins: 611725499

disqus: mybetterweb

# site configuration
profile: true
incremental: true
livereload: true
time_zone: Asia/Katmandul
destination: public
source:
markdown: kramdown
kramdown:
  hard_wrap : false
  input: GFM
  auto_ids: true
hightlighter: rouge
excludes: [ README.md, node_modules, Gemfile*, "LICENSE", ]
